// <auto-generated />
namespace YiHan.Cms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class merge_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(merge_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201710131158195_merge_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
